#![allow(dead_code)] // Stub implementations — will be replaced by tonic codegen

use hivemind_core::{Config, LayerRange, MicroToken, Tensor};
use hivemind_ledger::Wallet;
use std::net::SocketAddr;
use std::sync::Arc;
use tonic::{Code, Status};
use tracing::info;

/// Shared state injected into every gRPC request handler.
#[derive(Clone)]
pub struct ServerState {
    pub config: Arc<Config>,
    pub wallet: Arc<Wallet>,
    pub layer_range: LayerRange,
}

impl ServerState {
    pub fn new(config: Config, wallet: Wallet, layer_range: LayerRange) -> Self {
        Self {
            config: Arc::new(config),
            wallet: Arc::new(wallet),
            layer_range,
        }
    }
}

/// Processes an incoming activation tensor by running the local shard's forward pass.
///
/// In production this handler will be generated by tonic from `proto/activations.proto`.
/// Run `scripts/gen-proto.sh` to regenerate after modifying the proto definitions.
///
/// TODO: replace with `#[tonic::async_trait] impl ActivationService for ShardHandler`.
pub async fn handle_activation(
    state: &ServerState,
    input: Tensor,
) -> Result<Tensor, Status> {
    // TODO: enforce layer routing — reject requests for layers we don't own
    // TODO: call hivemind_shard::inference::forward_pass(input, &state.loaded_shard)
    let output = Tensor::zeros(input.shape.clone());

    let layers = state.layer_range.len() as u64;
    let seq_len = input.shape.first().copied().unwrap_or(1) as u64;
    state.wallet.earn(MicroToken(layers * seq_len));

    Ok(output)
}

/// Starts the gRPC shard server on `addr`.
///
/// The tonic service registrations below will be uncommented once proto codegen
/// is wired up via `build.rs`:
///
/// ```ignore
/// tonic::transport::Server::builder()
///     .add_service(ActivationServiceServer::new(ShardHandler::new(state.clone())))
///     .add_service(HealthServiceServer::new(HealthHandler::new(state.clone())))
///     .serve(addr)
///     .await?;
/// ```
pub async fn serve(addr: SocketAddr, state: ServerState) -> anyhow::Result<()> {
    info!(%addr, layers = %state.layer_range, "shard server starting");

    // Validate that tonic is wired in (will be replaced by real service registration)
    let _code = Code::Ok;

    // Placeholder: wait for shutdown signal
    // Real server will be a tonic::transport::Server loop
    tokio::signal::ctrl_c().await?;
    info!("daemon shutting down");
    Ok(())
}
